#!/usr/bin/env python3
"""
Auto-translate README.md (Chinese) into README.en.md (English).

Uses the DeepSeek API (OpenAI-compatible chat completions) with a
structure-preserving prompt: every HTML tag, badge URL, shields.io color,
markdown link, code span, number and statistic is kept byte-for-byte; only
human-readable Chinese text is translated into professional English.

Configuration (environment variables):
  DEEPSEEK_API_KEY   (required) DeepSeek API key.
  DEEPSEEK_BASE_URL  (optional) Default: https://api.deepseek.com
  DEEPSEEK_MODEL     (optional) Default: deepseek-chat

Run from the repository root:
  python .github/scripts/translate_readme.py
"""

import os
import re
import sys
import time
from datetime import datetime, timezone
from urllib.parse import quote

import requests

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
README_PATH = os.path.join(REPO_ROOT, 'README.md')
OUTPUT_PATH = os.path.join(REPO_ROOT, 'README.en.md')

API_KEY = os.environ.get('DEEPSEEK_API_KEY', '')
BASE_URL = os.environ.get('DEEPSEEK_BASE_URL', 'https://api.deepseek.com').rstrip('/')
MODEL = os.environ.get('DEEPSEEK_MODEL', 'deepseek-chat')

# English lines for the readme-typing-svg banner (replaces the Chinese lines
# deterministically, so the banner matches the language of the file).
EN_BANNER_LINES = [
    '🛡️ Security Hyacinth | InfoSec × AI Practitioner',
    '🔥 Forging the shields & spears of the AI era with code',
]

HEADER = (
    '<!-- ═══════════════════════════════════════════════════════════════════════════\n'
    '     AUTO-TRANSLATED: generated from README.md by .github/scripts/translate_readme.py\n'
    '     via DeepSeek API — do not edit this file manually.\n'
    '     ═══════════════════════════════════════════════════════════════════════════ -->\n\n'
)

SYSTEM_PROMPT = """You are a professional technical translator (Simplified Chinese -> English) with deep
knowledge of cybersecurity, AI/LLM engineering and open-source culture.

Translate the Markdown document from the user into natural, professional English.
Strict rules:

1. Translate ALL human-readable Chinese text into natural, professional English.
2. Preserve byte-for-byte: every HTML tag, attribute, style, URL, shields.io badge
   image, markdown link, image src/alt, code span, number, statistic, emoji and
   the '---' section separators.
3. shields.io badges (img.shields.io/badge/...): you MAY translate the human-readable
   LABEL and MESSAGE segments, but keep the HEX COLOR and every query parameter
   (?...) unchanged, and keep the exact format <LABEL>-<MESSAGE>-<COLOR> with
   spaces replaced by underscores (commas, '+' and digits stay as-is).
4. Keep technical brand names and acronyms in their canonical English form:
   HOS-LS, CTF, vLLM, MCP, RAG, PyPI, Hugging Face, CSDN, GitHub, Qwen2.5, LLaMA,
   FastAPI, React, Taro, TypeScript, Node.js, Docker, Git, CUDA, WSL2, Intel,
   CET-4, CET-6, Multi-Agent, Prompt Engineering, AIGC, etc.
5. Do not wrap the output in code fences, HTML comments or any extra text.
   Output ONLY the translated Markdown document.
6. Keep the overall structure, headings, tables and section order identical to
   the source. Do not add or remove any section."""

USER_PROMPT_TEMPLATE = """Translate the following Markdown document from Simplified Chinese into English.
Follow every rule in the system prompt exactly.

=== DOCUMENT START ===
{document}
=== DOCUMENT END ==="""


def english_banner_lines_encoded():
    """Percent-encode the English banner lines the same way as the Chinese ones."""
    return ';'.join(quote(line, safe='').replace('%20', '+') for line in EN_BANNER_LINES)


def replace_banner(content):
    """Swap the Chinese readme-typing-svg lines for the English ones (idempotent)."""
    pattern = re.compile(r'(https://readme-typing-svg\.demolab\.com\?[^"\s]*lines=)[^"\s]*')
    if pattern.search(content):
        content = pattern.sub(lambda m: m.group(1) + english_banner_lines_encoded(), content)
    return content


FOOTER_RE = re.compile(r'\n---\n\s*<div align="center">\n<sub>🤖.*?</sub>\n</div>\s*$', re.S)


def strip_footer(content):
    """Remove the machine-generated footer so the translator does not see timestamps."""
    m = FOOTER_RE.search(content)
    if m:
        return content[:m.start()].rstrip() + '\n', m.group(0)
    return content.rstrip() + '\n', ''


def call_api(payload):
    """Call the DeepSeek chat completions endpoint with retries."""
    url = f'{BASE_URL}/chat/completions'
    headers = {
        'Authorization': f'Bearer {API_KEY}',
        'Content-Type': 'application/json',
    }
    last_err = None
    for attempt in range(3):
        try:
            r = requests.post(url, headers=headers, json=payload, timeout=180)
            if r.status_code == 200:
                data = r.json()
                return data['choices'][0]['message']['content']
            last_err = f'HTTP {r.status_code}: {r.text[:500]}'
            if r.status_code in (429, 500, 502, 503, 504):
                time.sleep(2 ** attempt * 5)
                continue
            raise RuntimeError(last_err)
        except requests.RequestException as e:
            last_err = str(e)
            time.sleep(2 ** attempt * 5)
    raise RuntimeError(f'DeepSeek API request failed after 3 attempts: {last_err}')


def main():
    if not API_KEY:
        sys.exit(
            'DEEPSEEK_API_KEY is not set.\n'
            'Add it as a repository secret: GitHub -> Settings -> Secrets and '
            'variables -> Actions -> New repository secret -> DEEPSEEK_API_KEY.\n'
            'Then re-run this workflow (Actions -> "Translate README to English" -> '
            'Run workflow).'
        )

    with open(README_PATH, encoding='utf-8') as f:
        content = f.read()

    content = replace_banner(content)
    content, _ = strip_footer(content)

    payload = {
        'model': MODEL,
        'messages': [
            {'role': 'system', 'content': SYSTEM_PROMPT},
            {'role': 'user', 'content': USER_PROMPT_TEMPLATE.format(document=content)},
        ],
        'temperature': 0.3,
        'max_tokens': 8192,
    }

    print(f'Translating README.md with model "{MODEL}" ...')
    translated = call_api(payload).strip()

    now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')
    footer = (
        '---\n'
        '<div align="center">\n'
        f'<sub>🤖 This README is auto-updated and auto-translated by GitHub Actions | '
        f'Last updated: {now} UTC</sub>\n'
        '</div>\n'
    )

    output = HEADER + translated.rstrip() + '\n\n' + footer

    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write(output)
    print(f'✅ README.en.md written ({len(output)} characters)')


if __name__ == '__main__':
    main()
